"""Add username and user profile fields

Revision ID: b2c3d4e5f6a7
Revises: a5f2ca5f2a95
Create Date: 2025-09-09 00:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a5f2ca5f2a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=False, server_default='ENTREPRENEUR'))
        batch_op.add_column(sa.Column('business_stage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('interested_business_types', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preferred_areas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, server_default='1'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('preferred_areas')
        batch_op.drop_column('interested_business_types')
        batch_op.drop_column('phone')
        batch_op.drop_column('business_stage')
        batch_op.drop_column('user_type')
        batch_op.drop_column('nickname')
        batch_op.drop_column('username')
    
    # ### end Alembic commands ###
