version: "3.8"

services:
  sodam-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - JWT_SECRET_KEY=your-production-secret-key
      - DATABASE_URL=sqlite:///instance/app.db
    volumes:
      - ./instance:/app/instance
      - ./csv:/app/csv
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "https://port-0-sodam-back-lyo9x8ghce54051e.sel5.cloudtype.app/api/v1/market-diagnosis/markets",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  sodam-swagger:
    build: .
    command: python swagger_docs.py
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./csv:/app/csv
    restart: unless-stopped
    depends_on:
      - sodam-backend
